In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float

In [2]:
csv_file = "Data/2015.csv"
happiness_df = pd.read_csv(csv_file)
happiness_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [3]:
new_happiness_df = happiness_df[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity']]
new_happiness_df.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811

In [4]:
Base = declarative_base()
class Country(Base):
    __tablename__ = "2015" # required field
    country = Column(String(100), primary_key=True)
    happiness_rank = Column(Integer)
    happiness_score = Column(Float)
    economy  = Column(Float)
    family  = Column(Float)
    health = Column(Float)
    freedom = Column(Float)
    trust = Column(Float)
    generosity = Column(Integer)

In [5]:
rds_connection_string = "postgres:postgres@localhost:5432/happiness"
engine = create_engine(f'postgresql://{rds_connection_string}')
conn = engine.connect()

In [6]:
Base.metadata.create_all(conn)

In [7]:
new_happiness_df.to_sql(Country.__tablename__, conn, index=False, if_exists="append")

KeyError: 'Economy (GDP per Capita'